### PR TITLE
Rebased to upstream GNOME 3.38.1 docs release

### PR DESCRIPTION
**Pull request by pari-deshmukh**
Rebased with GNOME upstream upto commit - [b9fd749](https://github.com/endlessm/gnome-user-docs/commit/b9fd749c4c2be983c3fc93cd111431ef83cad3d0)

### CODE REVIEW

**Comment by andrunko** [comment]
I didn't have the time to check yet, but was there any conflict or anything of notice?

You will also need to update the debian-master branch accordingly.

**Comment by wjt** [comment]
ok to test

**Comment by pari-deshmukh** [comment]
Hi Andre,

Yes there were quite a few conflicts while rebasing with upstream master
however I resolved all of them and submitted the changes accordingly.

Kind Regards,
Pranali

**Comment by andrunko** [comment]
Closing this one as this was done manually.

**Pull request closed without merging**
