### PR TITLE
Update to 3.36.2-1 from debian bullseye

### PR DESCRIPTION
**Pull request by andrunko**
Update to latest packaging from debian (`3.36.2-1`).

It also includes one downstream change to **not** replace `install:` links with `apt:` links.

Source changes at https://github.com/endlessm/gnome-user-docs/pull/30.

https://phabricator.endlessm.com/T25587

### CODE REVIEW

**Comment by andrunko** [comment]
See https://github.com/endlessm/gnome-user-docs/pull/30#issuecomment-681284280 for the CI failure.

**Comment by andrunko** [comment]
bot, retest this please.

**Comment by andrunko** [comment]
> For gnome-control-center I changed the packaging branch to be based on the git branch used by Debian for packaging (in this case [here](https://salsa.debian.org/gnome-team/gnome-user-docs)). That has the advantage of keeping the commit history intact for changes that are made, and it means rebasing packaging is also a purely git operation like rebasing the code, but it does also mean slightly more work for you and we would be losing the history of our current packaging branch (although it has plenty of tags to retain it!). Up to you.
> 

While I tend to agree with you that it would be better I would prefer to go as is here now as I'd like to avoid spending more time here atm if that is Ok. We will probably do another round of rebases later when upstream releases again and by then we can check again.

> We also usually add an entry in the changelog with an `endless0` or `endless1` suffix, but I guess since this isn't the final rebase we can live without that.

Force pushed here to include the updated changelog - note it doesn't make much diff in the end for git maintained pkgs as the pkg version will be replaced anyway with devXX.<commit>...

**Comment by mwleeds** [comment]
LGTM

**Pull request closed without merging**
